// UTF-16 surrogate sanitization for text leaving the filesystem for an LLM request body.
//
// Vault notes / thread content can contain LONE (unpaired) surrogates — either from corrupt
// source files (e.g. iCloud-sync hiccups) or, more commonly, from a naive string.slice() that
// splits a surrogate pair at the boundary. A lone surrogate is invalid Unicode: JSON.stringify
// emits it as `\uD8XX`, and strict server-side JSON parsers (DeepSeek's, serde_json) reject it
// as a malformed / unpaired `\u` escape (surfacing as "unexpected end of hex escape"). These
// helpers keep LLM-bound text clean.

/**
 * Replace lone (unpaired) surrogates with U+FFFD so the text round-trips through JSON.stringify
 * without producing an unpaired `\u` escape. Paired surrogates (valid astral chars, e.g. emoji)
 * are preserved.
 */
export function stripLoneSurrogates(text: string): string {
  let out = ""
  for (let i = 0; i < text.length; i++) {
    const c = text.charCodeAt(i)
    if (c >= 0xd800 && c <= 0xdbff) {
      // high surrogate — valid only if followed by a low surrogate
      const n = i + 1 < text.length ? text.charCodeAt(i + 1) : NaN
      if (n >= 0xdc00 && n <= 0xdfff) {
        out += text[i] + text[i + 1]
        i++
      } else {
        out += "�"
      }
    } else if (c >= 0xdc00 && c <= 0xdfff) {
      // low surrogate without a preceding high → lone
      out += "�"
    } else {
      out += text[i]
    }
  }
  return out
}

/**
 * Slice to at most `max` code units WITHOUT splitting a surrogate pair: if the cut would leave
 * a dangling high surrogate at the end, drop it. Use this instead of `text.slice(0, max)` for
 * any preview/cap derived from arbitrary text.
 */
export function safeSlice(text: string, max: number): string {
  const s = text.slice(0, max)
  const last = s.length > 0 ? s.charCodeAt(s.length - 1) : 0
  if (last >= 0xd800 && last <= 0xdbff) return s.slice(0, -1) // drop dangling high surrogate
  return s
}

// ---------------------------------------------------------------------------
// <untrusted> injection marker (M2, §m2-untrusted-marker-rfc-2026-07-12)
//
// Tool results are DATA the model requested, never instructions to follow. But a
// hostile page can plant prompt-injection text in the DOM (visible text, alt, title,
// attribute values, evaluate return values) that flows back as tool-result content
// and — unmarked — becomes part of the agent prompt. wrapUntrusted() marks every
// tool-result content string with an <untrusted> boundary before it enters the LLM
// prompt, and the system prompt (basePrompt rule #11) instructs the model to treat
// the marked block as data. This is the input-side complement to the output-side
// capability gates (§6.1.5 analyze_image, §6.2 CRITICAL_API_GATE): marking raises
// the bar against novel injections the denylist sanitizer (page-sanitizer.ts) misses.
// ---------------------------------------------------------------------------

/**
 * Tools whose `data` payload is derived from web-page content (DOM text/HTML, page-JS
 * return values, screenshot/alt text, tab url/title, cookies). Tool results from these
 * carry the highest prompt-injection risk. Used to set source="page" on the <untrusted>
 * wrapper (vs source="tool" for companion-defined tools). A tool NOT in this set
 * degrades to source="tool" but is STILL wrapped — the wrap is universal (Option C);
 * the set only refines the source attribute for the model's reasoning.
 */
export const PAGE_CONTENT_TOOLS: ReadonlySet<string> = new Set([
  "get_page_text",
  "get_page_html",
  "get_element_info",
  "evaluate",
  "screenshot",
  "analyze_image",
  "analyze_image_fetch",
  "list_tabs",
  "create_tab",
  "navigate",
  "get_cookies",
  "list_all_cookies",
])

/**
 * Derive a deterministic, alphanumeric tag suffix from the tool_call_id. The closing
 * tag must be UNPREDICTABLE to the page: otherwise a hostile page could embed a
 * matching `</untrusted-XXX>` in its content and escape the marked block (kimi M2
 * review, scheme B). The tool_call_id is generated by the LLM/API and is never
 * visible to or controllable by the page, so a suffix derived from it cannot be
 * pre-embedded. Deterministic so a stored tool result gets the same suffix on every
 * replay (stable tags across regenerations). Tag names must be valid XML identifiers
 * → strip non-alphanumerics.
 */
function untrustedSuffix(toolCallId: string): string {
  const s = (toolCallId || "").replace(/[^a-zA-Z0-9]/g, "")
  return s.length > 0 ? s.slice(0, 24) : "x"
}

/**
 * Wrap a tool-result content string in an <untrusted> block before it enters the LLM
 * prompt. Per Option C, EVERY tool result is wrapped (tool results are data, never
 * instructions). The unique per-call tag suffix prevents a hostile page from embedding
 * a matching closing tag to escape the block. `source` is "page" for page-content
 * tools (highest injection risk) and "tool" otherwise.
 *
 * SECURITY: the caller MUST truncate BEFORE wrapping, so the closing tag is always
 * present — truncation must never drop `</untrusted-…>` and let content escape. The
 * wrap-after-truncate ordering is a security property, covered by tests.
 */
export function wrapUntrusted(content: string, toolCallId: string, toolName?: string): string {
  const suffix = untrustedSuffix(toolCallId)
  const source = toolName && PAGE_CONTENT_TOOLS.has(toolName) ? "page" : "tool"
  return `<untrusted-${suffix} source="${source}">\n${content}\n</untrusted-${suffix}>`
}
