// WebSocket peer authentication — shared-secret challenge–response.
//
// Closes the gap C1 / P0-2 deliberately left open: the WS Origin gate
// (isAllowedWsOrigin, server.ts) rejects web/foreign origins but CANNOT stop a
// local process from forging the `Origin: chrome-extension://...` header
// (curl -H) and then driving the agent over loopback — flipping
// security.auto_approve_dangerous, registering a malicious MCP server
// (mcp.add), draining history.export, etc. (server.ts:1418-1420 documents this
// deferral as "P2 / P0-2B".)
//
// This module implements P0-2B. On the first start the companion generates a
// 32-byte shared secret, persisted owner-only (0o600) in a file SEPARATE from
// config.json (which already holds llm.api_key — keeping the secret elsewhere
// shrinks the leak surface). The extension obtains this secret OUT-OF-BAND
// (first-run manual paste into Settings) — it is the one thing a local process
// forging the Origin header does not have.
//
// Handshake (per connection, post-upgrade):
//   companion → { type:"auth.challenge", nonce }   (fresh 16-byte nonce)
//   extension → { type:"auth.handshake", proof }    proof = HMAC-SHA256(secret, nonce) hex
//   companion → { type:"auth.ok" }                  then the app-level "connected" state
//   (bad/missing proof or no handshake within AUTH_TIMEOUT_MS → ws.terminate())
//
// The nonce makes each proof single-use, so a proof observed on the loopback by
// a sniffing local process cannot be replayed on a later connection (a static
// bearer would be replayable). The HMAC key is the UTF-8 bytes of the hex secret
// (matched exactly by the extension's Web Crypto importKey("raw", TextEncoder)).

import * as fs from "fs"
import * as path from "path"
import * as crypto from "crypto"
import { DATA_DIR } from "./config"
import { atomicWriteText } from "./io"

const SECRET_PATH = path.join(DATA_DIR, "ws_secret")

/** Peer must complete the handshake within this many ms or be terminated. */
export const AUTH_TIMEOUT_MS = 5000

let cachedSecret: string | null = null
/** Whether the secret was freshly generated by the most recent getOrCreate call
 *  (so the caller can log a first-run pairing instruction). Reset after read. */
let freshlyGenerated = false
/** Whether the most recent getOrCreate FAILED to persist the secret to disk.
 *  The in-memory secret still authenticates this process, but a restart will
 *  regenerate it and the extension must re-pair. Surfaced so the caller can log
 *  loudly. Reset after read. */
let persistFailed = false

/**
 * Get the long-lived shared secret, generating + persisting it on first use.
 * Idempotent: once generated (or loaded), returns the same value for the
 * process lifetime. Stored atomically (tmp + rename) at 0o600.
 */
export function getOrCreateSharedSecret(): string {
  if (cachedSecret) return cachedSecret
  try {
    const existing = fs.readFileSync(SECRET_PATH, "utf8").trim()
    if (existing) {
      cachedSecret = existing
      return cachedSecret
    }
  } catch {
    /* not yet generated — fall through */
  }
  cachedSecret = crypto.randomBytes(32).toString("hex")
  freshlyGenerated = true
  try {
    atomicWriteText(SECRET_PATH, cachedSecret + "\n", 0o600)
  } catch {
    // Persistence failure is non-fatal for THIS process (the in-memory secret
    // still authenticates), but means the next restart regenerates and the
    // extension must re-pair. Flag it so the caller can log loudly.
    persistFailed = true
  }
  return cachedSecret
}

/** True iff the most recent getOrCreateSharedSecret() created (vs loaded) the
 *  secret. Consumed (and reset) by the caller to emit first-run guidance. */
export function consumeSecretFreshlyGenerated(): boolean {
  const v = freshlyGenerated
  freshlyGenerated = false
  return v
}

/** Clear the in-memory secret cache + fresh flag (test isolation; mirrors
 *  config.ts's clearConfigCache). The next getOrCreateSharedSecret() re-reads
 *  (or regenerates) from disk. */
export function clearSecretCache(): void {
  cachedSecret = null
  freshlyGenerated = false
  persistFailed = false
}

/** True iff the most recent getOrCreateSharedSecret() could NOT persist the
 *  secret to disk. Consumed (and reset) by the caller to log loudly that the
 *  extension will need to re-pair after the next restart. */
export function consumeSecretPersistFailed(): boolean {
  const v = persistFailed
  persistFailed = false
  return v
}

/** Force-regenerate the secret (e.g. a "reset pairing" action). Existing
 *  connected peers remain authed until they reconnect; they will then fail and
 *  must re-pair. Returns the new secret. Also clears the .paired marker so the tray
 *  re-enters the first-run pairing flow (auto-surface the new secret). */
export function resetSharedSecret(): string {
  clearSecretCache()
  try { fs.rmSync(SECRET_PATH, { force: true }) } catch { /* ignore */ }
  try { fs.rmSync(PAIRED_PATH, { force: true }) } catch { /* ignore */ }
  return getOrCreateSharedSecret()
}

/** Read the current secret for display (settings-cli / pairing UI). Generates
 *  it if absent so pairing always has something to show. */
export function getSharedSecretForDisplay(): string {
  return getOrCreateSharedSecret()
}

const PAIRED_PATH = path.join(DATA_DIR, ".paired")

/** Path of the "has any peer ever paired" marker. Kept in lock-step with the tray's
 *  pairing.ts (same DATA_DIR / getConfigDir()). */
export function getPairedMarkerPath(): string {
  return PAIRED_PATH
}

/**
 * Best-effort: record that at least one peer has completed the WS handshake, so the
 * tray knows it can stop auto-surfacing the pairing secret. Idempotent — only writes
 * on the FIRST ever successful auth — and NEVER throws (a missing/unwritable marker
 * just means the tray treats the install as unpaired, which is the safe default). */
export function markPaired(): void {
  try {
    if (fs.existsSync(PAIRED_PATH)) return
    atomicWriteText(PAIRED_PATH, new Date().toISOString() + "\n", 0o600)
  } catch {
    /* never block pairing on marker persistence */
  }
}

/** Fresh per-connection challenge nonce (16 random bytes, hex). */
export function issueChallenge(): string {
  return crypto.randomBytes(16).toString("hex")
}

/**
 * Constant-time verification that `proof` equals HMAC-SHA256(secret, nonce).
 * Returns false on any mismatch (wrong proof, missing proof, length mismatch)
 * without leaking which via timing.
 */
export function verifyProof(secret: string, nonce: string, proof: string): boolean {
  if (!secret || !nonce || typeof proof !== "string" || !proof) return false
  const expected = crypto.createHmac("sha256", secret).update(nonce).digest("hex")
  const a = Buffer.from(expected, "utf8")
  const b = Buffer.from(proof, "utf8")
  if (a.length !== b.length) return false
  try {
    return crypto.timingSafeEqual(a, b)
  } catch {
    return false
  }
}
