# hello-verify.ps1 — Windows Hello verification via WinRT UserConsentVerifier.
# Callable unsigned (verified on Win11 build 10.0.28000 — no EV cert / UIAccess
# needed; the consent dialog is OS-hosted).
#
# Contract:
#   -ProbeOnly:   exit 0 + {"available":true} when Hello is usable; exit 3 otherwise.
#   normal:       exit 0 + {"verified":true,"nonce":"<echo of -Nonce>"} on success
#                 exit 3 → HELLO_UNAVAILABLE (DeviceNotPresent / NotConfigured /
#                          DisabledByPolicy / type load failure) — caller downgrades
#                          to manual-nonce
#                 exit 4 → user cancelled the Hello dialog (Canceled) — caller DENIES
#                          (no fallback)
#                 exit 5 → any other failure (stderr carries detail)
# The nonce is generated by the TS caller and echoed back for binding
# validation — the script never invents it.

param(
  [string]$Nonce = "",
  [string]$Reason = "Confirm host write",
  [switch]$ProbeOnly
)

[Console]::OutputEncoding = [Text.Encoding]::UTF8
$ErrorActionPreference = "Stop"

function Exit-Unavailable([string]$why) {
  [Console]::Error.WriteLine("HELLO_UNAVAILABLE:$why")
  exit 3
}

# --- Load WinRT types -------------------------------------------------------
try {
  Add-Type -AssemblyName System.Runtime.WindowsRuntime | Out-Null
  [Windows.Security.Credentials.UI.UserConsentVerifier, Windows.Security.Credentials.UI, ContentType=WindowsRuntime] | Out-Null
  [Windows.Security.Credentials.UI.UserConsentVerifierAvailability, Windows.Security.Credentials.UI, ContentType=WindowsRuntime] | Out-Null
  [Windows.Security.Credentials.UI.UserConsentVerificationResult, Windows.Security.Credentials.UI, ContentType=WindowsRuntime] | Out-Null
} catch {
  Exit-Unavailable "type-load: $($_.Exception.Message)"
}

# --- AsTask reflection bridge (PS 5.1 cannot await WinRT directly) ----------
$asTaskMethod = [System.WindowsRuntimeSystemExtensions].GetMethods() |
  Where-Object {
    $_.Name -eq 'AsTask' -and $_.IsGenericMethodDefinition -and
    $_.GetParameters().Count -eq 1
  } | Select-Object -First 1
if ($null -eq $asTaskMethod) {
  Exit-Unavailable "AsTask-method-not-found"
}

function Wait-WinRtAsync($operation, [Type]$resultType) {
  $asTask = $asTaskMethod.MakeGenericMethod($resultType)
  $task = $asTask.Invoke($null, @($operation))
  $task.Wait()
  return $task.Result
}

# --- Availability probe -----------------------------------------------------
try {
  $availOp = [Windows.Security.Credentials.UI.UserConsentVerifier]::CheckAvailabilityAsync()
  $avail = Wait-WinRtAsync $availOp ([Windows.Security.Credentials.UI.UserConsentVerifierAvailability])
} catch {
  Exit-Unavailable "check-failed: $($_.Exception.Message)"
}
# 0 = Available; 1 = DeviceNotPresent; 2 = NotConfiguredForUser;
# 3 = DisabledByPolicy; 4 = DeviceBusy
if ([int]$avail -ne 0) {
  Exit-Unavailable "$($avail.ToString())"
}

if ($ProbeOnly) {
  Write-Output (ConvertTo-Json -Compress -InputObject @{ available = $true })
  exit 0
}

# --- Interactive verification (OS-hosted dialog) ----------------------------
try {
  $verifyOp = [Windows.Security.Credentials.UI.UserConsentVerifier]::RequestVerificationAsync($Reason)
  $result = Wait-WinRtAsync $verifyOp ([Windows.Security.Credentials.UI.UserConsentVerificationResult])
} catch {
  [Console]::Error.WriteLine("HELLO_FAILED:$($_.Exception.Message)")
  exit 5
}

# 0 = Verified; 6 = Canceled; everything else → 5
if ([int]$result -eq 0) {
  Write-Output (ConvertTo-Json -Compress -InputObject @{ verified = $true; nonce = $Nonce })
  exit 0
} elseif ([int]$result -eq 6) {
  exit 4
} else {
  [Console]::Error.WriteLine("HELLO_FAILED:$($result.ToString())")
  exit 5
}
